########################################
# USER VARIABLES
PACKNAME = file.opx
SRC = file.opa
PLUGIN = file.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

EXE =
MAINSRC =

all: pack

include Makefile.common
