########################################
# USER VARIABLES
PACKNAME = tweetnacl.client.opx
SRC = tweetnacl.client.opa
PLUGIN = clientnacl.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
