########################################
# USER VARIABLES
PACKNAME = sso.opx
SRC = src/service.opa src/user.opa
PLUGIN =
PLUGINDIR = ./
OPAOPT = --parser js-like

EXE = sso_demo.exe
MAINSRC = src/main.opa

#Compiler variables
# OPACOMPILER ?= opa
# FLAG = --no-warn-error coding.todo --no-warn-error coding.deprecated
# OPADOC = opadoc
# PORT = 9000

all: pack

include Makefile.common
